### ISSUE TITLE
符号重复，链接错误

### ISSUE THREAD

**Issue by wulaitianc** [TuyaInc/tuyasmart_ios_sdk#1]
<img width="983" alt="screen shot 2017-07-27 at 8 00 01 pm" src="https://user-images.githubusercontent.com/17898549/28669275-36911624-7306-11e7-86de-63f485a1f66c.png">

**Comment by fisher12cc** [comment]
您好，感谢你的反馈，后续版本我们会把重复的地方修改掉，加上TY的前缀

**Comment by fisher12cc** [comment]
1.11.0 版本 已更新
