### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by 419860198** [TuyaInc/tuyasmart_ios_sdk#10]
启动一个野指针崩溃。在线程com.tuya.kTPMqttSubscribeServiceQueueName

YiShengYuePro`-[TYMQTTSession subscribeToTopics:subscribeHandler:]:
YiShengYuePro`-[TYMQTTSession subscribeToTopic:atLevel:subscribeHandler:]:
YiShengYuePro`__32-[MqttService subscribeToTopic:]_block_invoke:
libobjc.A.dylib`objc_msgSend:
libsystem_pthread.dylib`start_wqthread:

**Comment by 419860198** [comment]
启动时随机出现

**Comment by TuyaRonbin** [comment]
请提供更多的crash 堆栈信息。crash出现的概率多少？这个主要是三方库MQTTClient引起的。
