### ISSUE TITLE
How to get Tuya Device History

### ISSUE THREAD

**Issue by amacymind** [TuyaInc/tuyasmart_ios_sdk#11]
Hello,
I want my tuya smart device history data using ios sdk. But i can't able to find any method for that.
I am using door sensor so i want my device ON/OFF history even my app is closed.
Here i am using tried some methods from https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/en/resource/Device.html#get-historical-statistics-of-dp but it can't works.

So can you please help me on that?

Thanks,

**Comment by 0x5e** [comment]
Hi,
Not all device and all data point have history data, please enable the history data function in https://iot.tuya.com
Sorry for the inconvenience, we will update document for this question.

**Comment by amacymind** [comment]
Can you please tell me how to enable history function? because i already touch with tuya support but they can't able to help on this issue.

**Comment by 0x5e** [comment]
Hi, I've contacted internally and this function is not published yet. If you want enable this function please contact our project manager support, he knows how to enable manually.

**Comment by amacymind** [comment]
How can i contact your project manager?
Also one thing i want to told you is in your Tuya Smart iOS app my device get history data even app is closed.

**Comment by 0x5e** [comment]
https://iot.tuya.com => online consult 💬(right bottom)
