### ISSUE TITLE
Login issue 'Please upgrade your app to the latest version'

### ISSUE THREAD

**Issue by amacymind** [TuyaInc/tuyasmart_ios_sdk#12]
Hello,
When i try to login then its gives error like, 'Please upgrade your app to the latest version'

Thanks,

**Comment by 0x5e** [comment]
Hi,
We have 2 sdk: tuyasmart_ios_sdk and tuyasmart_home_ios_sdk, this means your account is create by tuyasmart_home_ios_sdk, then tuyasmart_ios_sdk can't be used.

**Comment by amacymind** [comment]
Okay. Can you please tell what is exact difference between both sdk?
So for which sdk prefer in which case.

**Comment by 0x5e** [comment]
`tuyasmart_home_ios_sdk` have the concept of home. device belongs to home, a home can have multiple members (administrator or not), you can share devices by add someone in the home.
`tuyasmart_ios_sdk` don't have home, device belongs to user. You can share devices directly to another user. This sdk is deprecated.
