### ISSUE TITLE
Hello, I installed TuyaSmartCamera through pod,It's added successfully but when I'm importing TuyaSnartCamera in my view controller it's giving error that No such module 'TuyaSmartCamera'

### ISSUE THREAD

**Issue by rajesh0092** [TuyaInc/tuyasmart_ios_sdk#13]

**Comment by 0x5e** [comment]
Did you mean https://github.com/TuyaInc/tuyasmart_camera_ios_sdk ?
If you are using swift, please create a oc header bridge file and import the sdk header.

**Comment by rajesh0092** [comment]
Ok Thanks, And for tuyasmartdoorlock what is the library..................

**Comment by 0x5e** [comment]
https://github.com/TuyaInc/tuyasmart_home_ios_sdk

**Comment by rajesh0092** [comment]
![screenshot 2019-03-05 at 4 32 37 pm](https://user-images.githubusercontent.com/48124413/53801138-5fea9780-3f64-11e9-875b-c4d43053cca3.png)
![screenshot 2019-03-05 at 4 32 52 pm](https://user-images.githubusercontent.com/48124413/53801149-68db6900-3f64-11e9-8a6b-8b44d27e7419.png)

On the above sdk smart camera calling functionality is not available.How can I use live camera functionality can you please suggest.

**Comment by tuyaLang** [comment]
tuyasmartdoorlock is also use TuyaSmartCamera sdk, and you need develop the panel by yourself.

**Comment by rajesh0092** [comment]
TuyaHomeSdk.getRequestInstance().requestWithApiName("tuya.m.ipc.config.get", "1.0", map, new IRequestCallback() {
    @Override
    public void onSuccess(Object o) {
        Log.e("response",o.toString());
        String  json_str=o.toString();
        Gson g = new Gson();
        Result result= g.fromJson(json_str,Result.class);

        Log.e("initStr", result.getP2pConfig().getInitStr()+"p2pkey"+result.getP2pConfig().getP2pKey());

        gotoDeviceControlActivity(finalP2pType,device_id,result.getP2pId(),local_key,result.getPassword(),result.getP2pConfig().getInitStr(),result.getP2pConfig().getP2pKey());

    }

    @Override
    public void onFailure(String s, String s1) {

    }
});


///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
In android you are passing the method like above I shared,In iOS how I will do the same thing??
How can I get p2pId & Password in iOS please suggest.........................

**Comment by tuyaLang** [comment]
Please refer to the document: https://tuyainc.github.io/tuyasmart_camera_ios_sdk_doc/en/resource/initiate_sdk.html

**Comment by rajesh0092** [comment]
Yaa Thanks,
Really I was searching this.....
Thanks Again.

**Comment by rajesh0092** [comment]
Hi,
request.request(withApiName: "tuya.m.ipc.config.get", postData: [
"devId": deviceModel.devId
], version: "1.0", success: { result in
print(result!)
}, failure: { error in
print(error!)
})

This api call not giving any response.Can you please check in your server what is the issue
