### ISSUE TITLE
Apple is suggesting to change UIWebView to WKWebview

### ISSUE THREAD

**Issue by thejaa** [TuyaInc/tuyasmart_ios_sdk#14]
Is SDK updated from UIWebView to WKWebView?.

**Comment by TuyaRonbin** [comment]
WebView is not included in SDK.

**Comment by thejaa** [comment]
Hello @xuchengcheng 

Thanks for reply.

https://github.com/TuyaInc/tuyasmart_ios_sdk/blob/master/Example/TuyaSmartKitDemo/Vendors/TYLibrary/Views/TPWebViewController.m

TPWebViewController.m file we have code of UIWebView. Apple is throwing message UIWebView is deprecated.

Note:- App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability.

**Comment by TuyaRonbin** [comment]
This is in the demo, not the SDK. 
WebView in demo will be changed immediately.
Thank you.

**Comment by thejaa** [comment]
@xuchengcheng ,

I thought that you are changing the UIWebView to WKWebView. You just removed the UIWebView.

While i am changing UIWebView to WKWebView. In WKWebView stringByEvaluatingJavaScriptFromString is deprecated i am stuck here.Can you please help me out on this.

I have used the code TPWebViewController.m in my project. 

Thank you.

**Comment by 0x5e** [comment]
https://stackoverflow.com/questions/56910707/wkwebview-stringbyevaluatingjavascriptfromstring-equivalent

**Comment by 0x5e** [comment]
@thejaa these issue can be found on stackoverflow, hope it can help you.

https://stackoverflow.com/questions/56910707/wkwebview-stringbyevaluatingjavascriptfromstring-equivalent
