### ISSUE TITLE
bug in MQTTClinet push update the podspec

### ISSUE THREAD

**Issue by louwangmonstar** [TuyaInc/tuyasmart_ios_sdk#5]
出错堆栈
0	libobjc.A.dylib
objc_msgSend + 16
1	MQTTClient
-[MQTTSession subscribeToTopics:subscribeHandler:] + 92
2	MQTTClient
-[MQTTSession subscribeToTopic:atLevel:subscribeHandler:] + 200
3	YiShengYuePro
___32-[MqttService subscribeToTopic:]_block_invoke + 180
4	libdispatch.dylib
__dispatch_call_block_and_release + 24
5	libdispatch.dylib
__dispatch_client_callout + 16
6	libdispatch.dylib
__dispatch_queue_serial_drain$VARIANT$mp + 528
7	libdispatch.dylib
__dispatch_queue_invoke$VARIANT$mp + 340
8	libdispatch.dylib
__dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 400
9	libdispatch.dylib
__dispatch_workloop_worker_thread$VARIANT$mp + 644
10	libsystem_pthread.dylib
_pthread_wqthread + 932

**Comment by TuyaRonbin** [comment]
The crash is likely to be caused by the libraries  [MQTTClinet](https://github.com/novastone-media/MQTT-Client-Framework)
