### ISSUE TITLE
Method: "dismissGroup" not working

### ISSUE THREAD

**Issue by sergey-zhuravel** [TuyaInc/tuyasmart_ios_sdk#6]
After calling the method "dismissGroup", each time it returns an error:
`finished with error - code: -999`

**Comment by 0x5e** [comment]
@zhuravel-sergey  Error code -999 means `NSURLErrorCancelled`, did you release the `TuyaSmartGroup` instance before network request completed?

**Comment by sergey-zhuravel** [comment]
how do I release the instance? This is not in your documentation, I do as you describe in the documentation
<img width="734" alt="screen" src="https://user-images.githubusercontent.com/7910769/39173709-2afb3fa6-47ae-11e8-8e3b-752a29237d85.png">

**Comment by 0x5e** [comment]
@zhuravel-sergey Please show me the code. I'm not sure if your `TuyaSmartGroup` instance was retained by your ViewController during the async operation. If not, the instance will be autoreleased in ARC(Automatic Reference Counting).

**Comment by sergey-zhuravel** [comment]
My code:
<img width="825" alt="screen" src="https://user-images.githubusercontent.com/7910769/39177517-319485b6-47b8-11e8-8c1f-e23f256bee01.png">

**Comment by 0x5e** [comment]
`TuyaSmartGroup *smartGroup = xxx;` was dealloc after `actionDeleteGroupButton` executed.

Strong reference `smartGroup` object like this:

```objc
@interface XXXViewController ()

@property (nonatomic, strong) TuyaSmartGroup *smartGroup;

@end

@implementation

- (void)dismissGroup {
    self.smartGroup = [TuyaSmartGroup groupWithGroupId:@"your_group_id"];
    [self.smartGroup dismissGroup^{
        // ...
    } failure:^(NSError *error) {
        // ...
    };
}

@end
```

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/MemoryMgmt.html
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html

**Comment by sergey-zhuravel** [comment]
thanks dude, it helped! ;)
