### ISSUE TITLE
LoginByEmail and RegisterByEmail return SING_VALIDATE_FALED_4

### ISSUE THREAD

**Issue by 0xChqrles** [TuyaInc/tuyasmart_ios_sdk#9]
Hi there,

I'm using your SDK in a Swift 4 application, I've set the appKey, secretKey and even the latitude and longitude, but when I try to login or register a new account I get `SING_VALIDATE_FALED_4`

```swift
@IBAction func login(_ sender: Any) {
	if let email = emailField.text, let password = passwordField.text {
		TuyaSmartUser.sharedInstance().login(byEmail: "33", email: email, password: password, success: {
			self.performSegue(withIdentifier: "tabBarUnwind", sender: self);
		}, failure: {optionalError in
			if let err = optionalError {
				print(err);
			}
		});
	}
}

@IBAction func register(_ sender: Any) {
	if let email = emailField.text, let password = passwordField.text {
		TuyaSmartUser.sharedInstance().register(byEmail: "33", email: email, password: password, success: {
			self.performSegue(withIdentifier: "tabBarUnwind", sender: self);
		}, failure: {optionalError in
			if let err = optionalError {
				print(err);
			}
		});
	}
}
```

thanks for your help

**Comment by 0x5e** [comment]
Hi, did you use the correct ios appkey & secret created from tuya ? Wrong appkey / secret may cause this error.
latitude and longitude is not required.

**Comment by 0xChqrles** [comment]
Thanks for you reply, I tried to change a character in the appKey to check if I get the same error, but I received a `ILLEGAL_CLIENT_ID`
Also, my appKey and secret work fine with the "SDK Demo"

**Comment by 0xChqrles** [comment]
Hi, I've tried the same thing in an Objective-C project and it works. Do you think it's possible to use the SDK in a Swift project?
I've also tried to use the SDK inside an Objective-C class but in a swift project and I get the same error

**Comment by 0x5e** [comment]
Could u please send the swift project include key/secret & test account/psw to my email(gaosen@tuya.com)? Sorry I can't reproduce the issue.

**Comment by 0x5e** [comment]
Hi, I've received your email, your appsecret doesn't match with appkey. I change the correct appsecret and the swift project works fine.
For safety reason, our server won't tell you directly "your appsecret is wrong". Sorry about the inconvenience :-)

**Comment by 0xChqrles** [comment]
Hi, I'm dumb as hell... now it works 😄, thanks for your help and your work

**Comment by ekinkaradagg** [comment]
@0x5e  Heyy  i have a problem about ILLEGAL_CLIENT_ID ı add the sha256 and check double app key and app secret but still not working:/ do you have any idea??
